export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  OFFICE: "/office",
  PROFILE: "/office/profile",
  USER: "/office/user",
  USERS: "/office/users",
  REG_REQUESTS: "/office/reg-requests",
  GROUPS: "/office/groups",
  GROUP: "/office/group",
  SUBJECTS: "/office/subjects",
  SUBJECT: "/office/subject",
  SECTIONS: "/office/sections",
  SECTION: "/office/section",
  LECTURES: "/office/lectures",
  LECTURE: "/office/lecture",
  TOPICS: "/office/topics",
  TOPIC: "/office/topic",
  TASKS: "/office/tasks",
  TASK: "/office/task",
  TASK_RESULTS: "/office/task-results",
};
